from __future__ import annotations

import functools

from dataclasses import dataclass


from ..game import Game
from ..game_objective_template import GameObjectiveTemplate

from ..enums import KeymastersKeepGamePlatforms


@dataclass
class AnyGameArchipelagoOptions:
    pass


class AnyGameGame(Game):
    """
    Shamelessly stolen from one of Petrichor's streams: https://www.youtube.com/watch?v=5e3JxxQDXVA
    """

    name = "Any Game Bingo"
    platform = KeymastersKeepGamePlatforms.META

    platforms_other = []

    is_adult_only_or_unrated = False

    options_cls = AnyGameArchipelagoOptions

    def optional_game_constraint_templates(self) -> list[GameObjectiveTemplate]:
        return []

    def game_objective_templates(self) -> list[GameObjectiveTemplate]:
        return [
        GameObjectiveTemplate(
                label="OBJECTIVE",
                data={"OBJECTIVE": (self.objectives, 1)},
                is_time_consuming=False,
                is_difficult=False,
                weight=3,
            ),
        ]

    def objectives(self) -> list[str]:
        return [
            "Go Through a Portal",
            "Kill Yourself 5 Times",
            "Fully Explore a Map",
            "Find An Egg",
            "Win The Game",
            "Jump Over 10 Cactuses",
            "Kill a Zombie",
            "Get An Upgrade",
            "Put On a Helmet",
            "Kill a Dragon",
            "Catch a Fish",
            "Use a Jetpack",
            "Get a Headshot With a Sniper",
            "Eat 10 Things",
            "Make a Trade",
            "Become Invisible",
            "Ride An Animal",
            "Kill a Person",
            "Complete The Tutorial",
            "Craft Something",
            "Grow And Harvest a Crop",
            "Sit Down",
            "Make 1,000,000$",
            "Level Up",
            "Get a Pet",
            "Score a Goal",
            "Serve a Customer",
            "Light a Furnace",
            "Defeat a Boss",
            "Commit Arson (Burn Down Someone's House)",
            "Build a House",
            "Cast a Spell",
            "Drink a Potion",
            "Find a Frog",
            "Do a Backflip",
            "Blow Up a Bomb",
            "Build a Turret",
            "Fly a Spaceship",
            "Kill Something Using The Environment",
            "Travel One Km",
            "Win a Battle Royale",
            "Play An Instrument",
            "Steal Some Treasure",
            "Kill a Friendly Npc",
            "See a Ghost",
            "Win a 1v1 (Online)",
            "Go To The Moon",
            "Use a Shovel",
            "Use a Computer In Game",
            "Crawl Through a Tunnel",
            "Play a Game Within a Game",
            "Complete a Side Quest For An Npc",
            "Fly Over a Forest",
            "Build a Campfire",
            "Glitch Out Of Bounds",
            "Explode Yourself",
            "Kill 10 Of The Same Thing",
            "Sleep Through The Night",
            "Have a Machine Craft Something For You",
            "Soft Lock Yourself",
            "Do today's Wordle",
            "Plant a Tree, And Watch It Grow",
            "Shoot Yourself",
            "Suffocate",
            "Ride a Boat",
            "Create a Creature",
            "Step On a Landmine",
            "Escape a Prison Cell",
            "Climb a Wall",
            "Enslave a Creature",
            "Get a Trophy",
            "Get a Perfect Score",
            "Have a Pet/Companion Kill Something",
            "Find a Dinosaur",
            "Take a Limb",
            "Make a Meal",
            "Set Every Slider To Max",
            "Fill Your Inventory",
            "Take Off Your Shirt",
            "Open a Treasure Chest",
            "Punch An Enemy",
            "Get To Exactly One Health",
            "Get Shot",
            "Draw a Card",
            "Use Magic",
            "Starve To Death",
            "Unlock a Cosmetic",
            "Lose It All By Gambling",
            "Flush a Toilet",
            "Pet a Dog",
            "Go Back In Time",
            "Draw a Pretty Picture",
            "Do a Lap In a Race",
            "Get In An Ocean",
            "Solve a Puzzle",
            "Go On a Date",
            "Roll a Dice",
            "Deal Critical Damage",
            "Reach The Credits Through Gameplay",
            "Fail a Quest",
            "Name a Pet",
            "Kill The Final Boss",
            "Fall To Your Death",
            "Climb a Ladder",
            "Parry An Attack",
            "Automate Something Indefinitely",
            "Solve a Puzzle",
            "Reach An In Game Save Point (Physical object)",
            "Become Intoxicated (Drink)",
            "Drink Water",
            "Get Full Armour",
            "Acquire Honey",
            "Grow Taller/Get Bigger",
            "Become Blinded Even Temporarily",
            "Become Poisoned",
            "Step On a Trap",
            "Catch a Projectile/Thrown Item",
            "Fill Entire Inventory",
            "Paint Or Dye Something",
            "Break One Of Your Limbs",
            "Crash a Game",
            "Die In 3 Different Ways In a Single Game",
            "Restore Health",
            "Touch Grass",
            "Hit The World Border/Invisible Wall",
            "Set Yourself On Fire",
            "Find An Easter Egg",
            "Find a Glitch",
            "Get a Kill Streak",
            "Spend All Your Money",
            "Open a Door",
            "Fight a Bird",
            "Pick Up a Creature (As In Hold It In Your Hand, Can't Be Something Like a Pokeball)",
            "Crash a Car",
            "Stand On a Rooftop",
            "Use a Yo-Yo",
            "Teabag a Fallen Foe",
            "Get An Extra Life",
            "Use Fast Travel",
            "Make a Phone Call",
            "Skip a Cutscene",
            "Do Not Skip a Cutscene",
            "Sit On a Bench",
            "Cut Down a Tree",
            "Electrocute Yourself",
            "Emote",
            "See Your Character's Reflection In a Mirror (No Cutscenes)",
            "Hitless a Boss",
            "Get Something Labeled As Rare",
            "Get An Item Name That Starts With The Letter Q",
            "Kill a Hydra",
            "Visit Space",
            "Command An Army",
            "Perform a Transformation",
            "Find Something Behind a Waterfall",
            "Break Glass",
            "Alter The Flow Of Traffic",
            "Fish Up Something That'S Not a Fish",
            "Complete a Skillcheck",
            "Ragdoll Something",
            "Complete a Daily Challenge",
            "Stand On a Conveyor Belt",
            "Have Something Die Of Old Age",
            "Get Over-Encumbered",
            "Beat a Roguelike Run",
            "Get a Jumpscare",
            "Double Jump",
            "Break An Item",
            "Jump Onto a Moving Object",
            "Read a Book",
            "Build a Bridge,",
            "Hide In a Closet",
            "Look In a Trash Can",
            "Dig a Hole",
            "Get Married",
            "Assassinate/Stealth Kill An Enemy",
            "Go To Another Dimension",
            "See/Hear a Thunderstorm",
            "Cross The Entire Map",
            "Commit a Crime",
            "Get 10,000 Of Something",
            "Flirt With An Npc",
            "Use a Shield",
            "Buy Everything From a Shop",
            "Get a One Of a Kind Item",
            "Capture a Creature",
            "Find a Hidden Area",
            "Die To a Sea Creature",
            "Win At Gambling",
            "Find God",
            "See Blood In Game",
            "Get The Game To Deny You From Doing Something",
            "Kill 10 People Without Them Noticing",
            "Make a Barricade",
            "Clear a Dungeon",
            "Get Cursed",
        ]
